# Generated by Django 5.1.1 on 2024-11-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registroentradasalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradasalida',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
